### ISSUE TITLE
[Feature Request] Reroll Initiative as per CUB

### ISSUE THREAD

**Issue by miromonti** [ironmonk88/monks-combat-details#13]
Let's add the option to reroll initiative between every combat round. It's a feature in CUB that I happily employ in all my 5e games. It is also the _only feature_ in CUB that I use. I'd prefer to have this option in Monk's Combat Details, whose features I take full advantage, instead of wasting CUB that I hardly use.

**Comment by ironmonk88** [comment]
Added tot he latest release.
