### ISSUE TITLE
Hide until turn setting is not working on the pf2e system

### ISSUE THREAD

**Issue by manomarthas** [ironmonk88/monks-combat-details#15]
Since the fragmantation of Monk's Little Details into various modules, the "Hide until turn" setting of Monk's Combat Details is not working properly on the pf2e system. All npcs appear instantly to the players on the encounter window when combat starts showing their initiative value. 

Tested on the pf2e system version 4.8.3 on a new world with only Monk's Combat Details enabled.

**Comment by DieterKosken** [comment]
+1

**Comment by ironmonk88** [comment]
I believe this has been fixed?

**Comment by ironmonk88** [comment]
Closing this as I can't replicate, and there's been no response.
