### ISSUE TITLE
[Bug] .message.round-marker is hidden

### ISSUE THREAD

**Issue by yjeroen** [ironmonk88/monks-combat-details#16]
Issue: The message-content of the new round marker isn't shown in the chat:
![image](https://user-images.githubusercontent.com/1303988/224307181-b8187012-1c8b-4cbf-9cb1-d8fad191b1e7.png)

This is due to `display:none` in the css:
![image](https://user-images.githubusercontent.com/1303988/224307272-709bffe3-4c74-4cb0-a739-8cb58897bce2.png)

Expected:
![image](https://user-images.githubusercontent.com/1303988/224307098-65fde3d5-4938-4779-bc2f-c18d628de38d.png)

**Comment by yjeroen** [comment]
The css should be: `display: inline;`

**Comment by yjeroen** [comment]
Ah nevermind, I see.. I think you meant to hide the message-header instead to have the same functionality as before:

```css
#chat-log .message.round-marker .message-header {
	display: none;
}
```

**Comment by ironmonk88** [comment]
What system is this for?

**Comment by yjeroen** [comment]
Pf2e

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/224365583-a3324fcf-44dc-4283-8001-46fdc82704a8.png)
It's working properly for me.
Can you run FTC to make sure it's not another module causing interference?

**Comment by yjeroen** [comment]
Ah yes I thought I had done that, apologies.

Compatibility cause is PF2e Dorako UI. Not sure what update (them or yours) caused this issue, as it was working before.

**Comment by yjeroen** [comment]
With PF2e Dorako UI disabled:
![image](https://user-images.githubusercontent.com/1303988/224537102-1a112cdc-773e-4bcf-991f-05819672f5b4.png)

With PF2e Dorako UI enabled:
![image](https://user-images.githubusercontent.com/1303988/224537119-964feb5e-4b04-4a0c-9d59-54052ed2cf6f.png)

Kind of weird the flavor-text message is on a different structure spot in the html.

**Comment by ironmonk88** [comment]
I believe the PF2e Dorako UI has fixed this.

**Comment by ironmonk88** [comment]
Closing this as I believe the issue no longer exists.
