### ISSUE TITLE
[Feature Request] A Way to Set Custom Initiative Turn Order sounds per Player/Token

### ISSUE THREAD

**Issue by Sherbniz** [ironmonk88/monks-combat-details#17]
This isn't really important and it's not necessary if it's hard to implement, but it would be kind of sweet to be able to set a different initiative turn sound for each player.
So for instance the Bard gets called to action by a lute-strum, the warrior by a shield bash noise, the artificer by a steam whistle...

If it was a setting per Token it would be even more flexible, then the demon gives you an evil laugh on his turn, or the spider lets out a menacing chitter!

Just a thought, if it's too hard to do or you feel like it's unnecessary just ignore this! I love your modules, they're bloody awesome! Thanks for all the hard work!

**Comment by ironmonk88** [comment]
You'd want Monk's Sound Enhancements for that.
![image](https://github.com/ironmonk88/monks-combat-details/assets/75920956/673181e4-140a-45db-8d0d-404722018f83)

**Comment by ironmonk88** [comment]
Closing this as it exists in one of my other modules.
