### ISSUE TITLE
Support for CyberpunkRED core

### ISSUE THREAD

**Issue by aruguy** [ironmonk88/monks-combat-details#19]
The CyberpunkRED system uses a unique datapath for HP that conflicts with the module automatically flagging a token as defeated.

CyberpunkRED uses `system.derivedStats.hp.value` and `system.derivedStats.hp.max`

Would it be possible to add a field that allows users to point to an alternative location for HP stats?

**Comment by ironmonk88** [comment]
Updated in the latest release.
