### ISSUE TITLE
PF2e Combat Difficulty Not Calculating Correctly

### ISSUE THREAD

**Issue by rmressler** [ironmonk88/monks-combat-details#2]
I love the combat difficulty calculator, but as a PF2e GM it's not calculating correctly. Calculations should be done based on [the encounter building rules](https://2e.aonprd.com/Rules.aspx?ID=497) but right now seem to be a bit off. For example, an encounter with 4 party members at level 4 vs. 2 creatures at level 4 should be moderate (2 at party level creatures worth 40xp each = 80xp for spot on moderate), but is currently calculating as Severe.

**Comment by ironmonk88** [comment]
Added to the latest release.
