### ISSUE TITLE
[BUG] Interaction between Alternative Token vision and Monk's Combat Details' "Show Start Token" setting: Soundwave overlay effect is applied to current combatant

### ISSUE THREAD

**Issue by MS-PBS** [ironmonk88/monks-combat-details#20]
**Describe the bug**
When in combat, if ATV is active and MCD's "Show Start Token" setting is enabled, the moving token gets the soundwave overlay effect that applies when a token is hidden.

**To Reproduce**
1. Have Alternative Token Vision and MCD (and dependencies) active. 
2. Make sure that "Show Start Token" is enabled.
3. Start a combat and move the current combatant
4. The soundwave overlay effect for hidden tokens (the one added on Foundry V10) will be applied to the current combatant.

**Expected behavior**
No overlay should be applied. It doesn't make sense to apply this effect to the token you're currently controlling.

**Screenshots**

https://user-images.githubusercontent.com/68601994/226176237-09c28bc7-0e94-4889-813d-213b41d5f30a.mp4

**Please complete as much of the following information as possible:**
 - Browser: Firefox
 - Foundry Version 10 b 291
 - System: PF2e
 - Module version: 10.1
 - Are there any errors in the console? -> No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction -> It is a module interaction but I'm hoping it can be solved if there's something you can do on your end. Otherwise it's at least interesting.

**Context**

I also reported this on ATV's page: https://github.com/caewok/fvtt-token-visibility/issues/39

**Comment by caewok** [comment]
Hi! I am the dev for Alt Token Visibility module, and I am a bit at a loss as to how ATV and Monk's is interacting. My best guess is that this [visibility test](https://github.com/ironmonk88/monks-combat-details/blob/d0e851417ed8f84a72bd4b0d23271385e8f0fb5a/js/combat-turn.js#L208) is not doing what Monk's assumes it does:

```js
        Hooks.on("sightRefresh", function () {
            for (let [id, shadow] of Object.entries(CombatTurn.shadows)) {
                let token = canvas.tokens.get(id);
                if (token) {
                    const tolerance = Math.min(token.w, token.h) / 4;
                    shadow.visible = canvas.effects.visibility.testVisibility({ x: shadow.x, y: shadow.y }, { tolerance, object: token });
                }
            }
        });
```

ATV defines alternative tests for whether a token can see another token. It is only done for token objects. So my guess is that here, the visibility test for the shadow is using whatever the user sets the test to be in ATV. If that is the case, a simple solution might be to either pass some object other than token, or to coordinate to add some sort of option that ATV can pick up on to let the default test go for this one. 

When you get a chance to review, feel free to respond here or ping me on Discord (caewok#9192).

**Comment by ironmonk88** [comment]
Fixed in the latest release.
