### ISSUE TITLE
[BUG] Show Starting Location not working for player.

### ISSUE THREAD

**Issue by BasiliskOnline** [ironmonk88/monks-combat-details#21]
When I start combat, as a GM I can see the show start token, However, while im alt logged as a player (simultaneously) to check how everything is working. I notice the "show starting token" doesn't display for the character.

GM View:
![image](https://user-images.githubusercontent.com/27906526/227383857-0ca007e4-5f0f-4d0e-b08d-0e9eca4874e1.png)

Player View:
![image](https://user-images.githubusercontent.com/27906526/227383896-31c9afa8-7182-409f-adad-ce5bafb0ac3b.png)

Browser is Chrome
Foundry v 10 (on Forge)
Pathfinder 2E
Module version 10.1
No errors for your module there
No other modules active.

Thanks so much!

**Comment by ironmonk88** [comment]
Fixed in the latest release.
