### ISSUE TITLE
FR: (option to) Popout Combat tracker when combat is created, vs when started

### ISSUE THREAD

**Issue by esheyw** [ironmonk88/monks-combat-details#22]
Right now, the 'Switch to Combat Tab' setting only applies to the GM; this is fine, I don't want my players to have to switch tabs, that's the point of the popout tracker workflow. 
My issue is, I guess they're assumed to be rolling initiative from their sheet? But between Token Action HUD and various other modules, they really don't have to have their sheets open for much in combat, and I don't want to make this an exception, and there's a perfectly good 'roll initiative' button in the tracker. If the tracker popped out on combat creation, instead of combat start, they don't need to open their sheet *or* change tab. 
Currently working around this by providing a roll initiative macro, but bar space is precious, and this would free up a slot.

**Comment by ironmonk88** [comment]
Added to the latest release.
