### ISSUE TITLE
[BUG] Combat Bars can't be enabled on tokens

### ISSUE THREAD

**Issue by RossGosling** [ironmonk88/monks-combat-details#24]
**Describe the bug**
I've enabled `Add Combat Bars`, which adds a new dropdown menu to tokens, when editing said dropdown the value is never saved and never functions

**To Reproduce**
1. Enable `Add Combat Bars`
2. Create an actor
3. Set the token's `Combat Display Bars` option to anything
4. Update Token
5. Open the token's settings and witness an empty `Combat Display Bars` option

**Expected behavior**
The `Combat Display Bars` option should be saved and work as described for whichever is selected

**Screenshots**
Adjusting my prototype (same for token instances)
![image](https://user-images.githubusercontent.com/879127/229935823-1bca72ba-f64a-4627-88ca-2bcafa7f8a80.png)
Returning to view after saving closes the menu to find it empty
![image](https://user-images.githubusercontent.com/879127/229935850-5b25249b-e917-46cb-afcb-5a8c5a4db63e.png)

**Please complete as much of the following information as possible:**
 - Browser Firefox
 - Foundry Version v10 Build 291
 - System D&D5e 2.15
 - Module version 10.2
 - No errors in the console

**Comment by ironmonk88** [comment]
Closing this as there's been no response and I no longer support the v10 versions.
