### ISSUE TITLE
[Feature Request] Customize the Turn/Round Messages

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#26]
A module setting to edit the text displayed in the turn/round messages and notifications.

Per-user. 

> In Monks Combat Details, I was pondering if I could possibly edit the turn and round messages so that I could somehow plop in messages for the players.  Mainly something like:  "Turn 1 ends, Player 1 describe how your turn played out to us"  Maybe this is a bad fit for Monks stuff but its the only thing I'm aware of that currently hooks into turns effectively, I suppose I could do an effect macro on each players character to pull this off too.

**Comment by ironmonk88** [comment]
Added to the latest release.
