### ISSUE TITLE
[Feature Request] Add language support for Turn messages

### ISSUE THREAD

**Issue by Scaby79** [ironmonk88/monks-combat-details#27]
The chat messages for  the turns are hard coded in the combat-turn.js in the following locations

line 50
line 139
line 141

If you could add language support via localize the messages could be translated.

I would appreciate this very much.

Thx in advance.

**Comment by Scaby79** [comment]
In addition this would enable users to edit the messages individually as requested here: https://github.com/ironmonk88/monks-combat-details/issues/26

**Comment by Scaby79** [comment]
Maybe you could add language support for the initiative dialog too. 

This could be done in the file monks-combat-details.js  in the lines 114 and 115.

Thx again.

**Comment by ironmonk88** [comment]
Added to the latest release.
