### ISSUE TITLE
Hide Monster and NPC Actor/Token names in Chat Cards and Combat Tracker

### ISSUE THREAD

**Issue by Bedwards6594** [ironmonk88/monks-combat-details#28]
I would like to have the names hidden in the chat card results and combat tracker without having to manipulate Represented Token name/Actor Name/Character Name all the time. Was wondering if in the chats and tracker, it just showed the token icon. Similar to what I have seen in Combat Utility Belt feature.

**Comment by ironmonk88** [comment]
Closing this as the module Anonymous handles it better.
https://github.com/reonZ/anonymous
