### ISSUE TITLE
[BUG] Players have blank Combat Encounter

### ISSUE THREAD

**Issue by Bedwards6594** [ironmonk88/monks-combat-details#30]
**Describe the bug**
The Combat Encounters tab does not display in Players' screens. Does not popout.
(Also- players can move their tokens when it is not their turn)

**To Reproduce**
Module enabled for Switch to Combat Tab; Popout Combat Dialog set to Everyone; Combat Dialogue position set to Top Right. Combat begins and players are unable to see initiative order and have blank Comabt Encounter Tab.

**Expected behavior**
Combat Encounter displays as expected

**Screenshots**
![DMScreen](https://github.com/ironmonk88/monks-combat-details/assets/68972464/bf73c01e-a914-46ab-b1db-a9bb8c070a97)
![PLayer screen](https://github.com/ironmonk88/monks-combat-details/assets/68972464/2919c470-52da-460c-a633-57e1dbf9bd9e)

**Please complete as much of the following information as possible:**
 - Browser DM using Firefox; players using Chrome and Firefox
 - Foundry Version v10
 - System 3.5SRD v 2.1.3
 - Module version 10.2
 - Are there any errors in the console [e.g. press F12 and look for red text] Not sure if these are right-but they're red and they mention Monk
 - monks-bloodsplats.js:166 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'round')
[Detected 2 packages: monks-bloodsplats, system:D35E]
    at Object.fn (monks-bloodsplats.js:166:43)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at CombatD35E.deleteEmbeddedDocuments (combat.js:215:11)
    at async CombatD35E.removeBuffFromCombat (combat.js:356:7)
monks-combat-details.js:375 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'active')
[Detected 2 packages: monks-combat-details, system:D35E]
    at MonksCombatDetails.checkPopout (monks-combat-details.js:375:46)
    at Object.fn (monks-combat-details.js:458:24)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at CombatD35E.deleteEmbeddedDocuments (combat.js:215:11)
    at async CombatD35E.removeBuffFromCombat (combat.js:356:7)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. no

**Additional context**

![PLayer screen](https://github.com/ironmonk88/monks-combat-details/assets/68972464/d11e6331-8619-45f2-afa3-3cb5000a5ae2)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
