### ISSUE TITLE
[API] Move logic for hiding combatants to a wrapper

### ISSUE THREAD

**Issue by theripper93** [ironmonk88/monks-combat-details#31]
The logic that hides combatants from the combat tracker from these 2 options should be moved to a wrapper of the `Combatant.prototype.visible` so that other modules operating with the combat tracker (such as Carousel Combat Tracker) will read these changes accordingly without any need of explicit compatibility.

The two features in question:
![image](https://github.com/ironmonk88/monks-combat-details/assets/1346839/ac86a33f-54c7-4854-a66f-2cbba7e95120)

As an alternative, wrap the `Combat.prototype.setupTurns` instead

**Comment by ironmonk88** [comment]
Added to the latest release.
