### ISSUE TITLE
[BUG] Deleting combatants retriggers "Up Next" and "Your Turn" notifications

### ISSUE THREAD

**Issue by nschoenwald** [ironmonk88/monks-combat-details#32]
**Describe the bug**
When the GM deletes combatants, notifications and sounds are retriggered for players if it's their turn or they are up next.

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: v10
 - System: dnd5e
 - Module version: current

**Comment by roi007leaf** [comment]
I think this doesnt relate to deleting, i get this on every npc turn even though the setting for the sounds is turned off

**Comment by ironmonk88** [comment]
Fixed in the latest release
