### ISSUE TITLE
Temporary Combatants

### ISSUE THREAD

**Issue by MrZeyami** [ironmonk88/monks-combat-details#34]
I'm requesting that the temporary combatant functionality of CUB be taken over here, as I do find it very useful for things like Lair Actions, Hazards, and just general placeholders that I don't want to build dummy sheets for. I've not found a single utility or module which replicates this feature, which honestly is a little surprising. It's a very common tool in other VTTs.

**Comment by ironmonk88** [comment]
Added to the latest release.
