### ISSUE TITLE
[BUG] Mark Combatants Defeated

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#35]
Errors and fails when its a PC.

https://github.com/ironmonk88/monks-combat-details/assets/99844555/65f5dcdc-9ea1-4918-869b-bf514633b0c0

Slightly different error in 5e. Same result though.

![image](https://github.com/ironmonk88/monks-combat-details/assets/99844555/cc4a4138-6da7-44eb-956b-f661389c7658)

Foundry 11.304
5e 2.2.1
PF2 5.0.2
Combat Details 11.01

**Comment by ironmonk88** [comment]
Fixed in the latest release.
