### ISSUE TITLE
10.2 not updating to 11.02

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-combat-details#37]
Currently using Foundry v10.303 on The Forge. Noticed that Combat Details was updated to 11.02 recently but information on The Forge is still indicating 10.2 is latest. Does the newest version require Foundry v11? Can't do that yet because my gaming system (PF1e) doesn't support the newest Foundry.

**Comment by ckdragons** [comment]
Forge is still reporting 10.2 as latest version.
![image](https://github.com/ironmonk88/monks-combat-details/assets/84493092/dbbbd669-da81-4b57-9c39-253fb39d9e30)

**Comment by ironmonk88** [comment]
It's working correctly for me.
![image](https://github.com/ironmonk88/monks-combat-details/assets/75920956/527126f6-4bfe-4534-8d7a-5fad683c6e15)

**Comment by ckdragons** [comment]
Possible because I'm still only on Foundry v10? I noticed the same thing with some of your other mods, most have an update available but it's not reported as being available in the The Forge.

**Comment by ironmonk88** [comment]
It would 100% be because you're still on v10.  Missed that in the original post.
All my v11 updates only work on v11.  There's just too many significant changes in Foundry to be able to support backwards compatibility.
