### ISSUE TITLE
[BUG] Token Ghosts Stuck

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#39]
Whoever isn't the one moving the token gets the extra ghosts.

Video doesn't show it, but ending turns/combat doesn't remove the ghosts either.

https://github.com/ironmonk88/monks-combat-details/assets/99844555/01b40e0a-0cc2-40d1-a11b-3ae21c055897

Foundry 11.304
Combat Details 11.02

**Comment by ironmonk88** [comment]
Fixed in the latest release.
