### ISSUE TITLE
Auto scroll on Combat Tracker is no longer working

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-combat-details#40]
This option is no longer working.
![image](https://github.com/ironmonk88/monks-combat-details/assets/84493092/4cd04b86-8025-4e43-91f9-b8e1bd86ca04)

Have more combatants than will fit in the Combat Tracker.
![image](https://github.com/ironmonk88/monks-combat-details/assets/84493092/68f2a519-a3e7-48da-b496-9f85068051da)

Click Next Turn and the list doesn't adjust.
![image](https://github.com/ironmonk88/monks-combat-details/assets/84493092/623f2b7e-ec5c-4779-844e-98e3db4fcc2c)

![image](https://github.com/ironmonk88/monks-combat-details/assets/84493092/67c28947-8db5-4cab-ab46-9a60a0bc4be5)

![image](https://github.com/ironmonk88/monks-combat-details/assets/84493092/a62aeb95-5859-4d48-ad06-e1794dc413e4)

**Comment by ironmonk88** [comment]
I **think** there was a problem with it in v10.  I can't remember.
It seems to be working in v11 though, and I can't really debug earlier versions unfortunately.
If you upgrade to v11 and it's still an issue, let me know.
