### ISSUE TITLE
[BUG] Tracker not opening Pf2e

### ISSUE THREAD

**Issue by uniwars** [ironmonk88/monks-combat-details#41]
**Describe the bug**
The combat tracker is set to open when combat begins for everyone (same with only gm) but it doesn't. After a F5 it will be open or by right clicking the encoutner tab as by defaut without the module.

**To Reproduce**
1. Add combattants to encounters (tested with only pc, and pc and npc)
2. Roll initiative for all
3. Click on Begin combat

**Expected behavior**
The reduce encoutner tab should open.

**Please complete as much of the following information as possible:**
 - Foundry Version 11 306
 - System Pathfinder 2 5.2.3
 - Module version last
 - Are there any errors in the console -> No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. -> Yes

**Additional context**
It may come from 5.2.x system update which change some naming and broke compatibility with some modules.

If the combat begins without rolling initiative it will works, it doesn't work after rolling initiative.
There may be other issues due to pf2e system last updates that I didn't notice too.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
