### ISSUE TITLE
Remember position and size of the tracker

### ISSUE THREAD

**Issue by uniwars** [ironmonk88/monks-combat-details#42]
**Describe the solution you'd like**
Hi, that would be nice if the module could save the position we moved the tracker and if we resized it to overwrite the basic "top left" spawn point of the tracker for example.

For example to get it like this each time it opens without having to move it there and then resize it to get it a little bit smaller :
![image](https://github.com/ironmonk88/monks-combat-details/assets/65986545/c2fb7fe3-f3c1-4ee3-88d9-ad0a93115a73)

**Comment by ironmonk88** [comment]
Added to the latest release.
