### ISSUE TITLE
Auto open/close character sheets during combat

### ISSUE THREAD

**Issue by ditzer252** [ironmonk88/monks-combat-details#44]
Please consider adding features that were in the [NextUp](https://github.com/kandashi/Next-Up) mod, which seems to be abandoned. 
It is very convenient to have character sheets automatically open and close off to the side, or in a corner of the screen during a combat, and I think this fits into the scope of monks-combat-details.  Thank you.

**Comment by ironmonk88** [comment]
Fixed in the latest release
