### ISSUE TITLE
[BUG] 11.04 wont "let go" of player cameras

### ISSUE THREAD

**Issue by MythicalRollers** [ironmonk88/monks-combat-details#46]
**Describe the bug**
With 11.04 installed.  Pop out a camera from the dock, then click on it to move it.  You are unable to "let it go" to put it in place.  Down grading to 11.03 resolves this.  Console error attached.

**To Reproduce**
1. Go to 'Pop out a camera from the default dock'
2. Click on 'Click and drag it to move it'
3. Try to place it where you want.

**Expected behavior**
I expected to be able to move the cameras where I wanted them

**Screenshots**
N/A

**Please complete as much of the following information as possible:**
 - Browser [Chrome]
 - Foundry Version [V11]
 - System [D&D5e: 2.3.0]
 - Module version [11.04]
 - Are there any errors in the console:
 monks-combat-details.js:212 Uncaught (in promise) TypeError: this.app.constructor._getInheritanceChain is not a function or its return value is not iterable
    at 🎁Draggable.prototype._onDragMouseUp#monks-combat-details (monks-combat-details.js:212:52)
    at 🎁Draggable.prototype._onDragMouseUp#0 (libWrapper-wrapper.js:187:52)
    at handlers.dragUp (foundry.js:65211:55)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. (No, because if I go to 11.03 this error is resolved.)

**Additional context**

**Comment by ironmonk88** [comment]
Fixed in the latest release.
