### ISSUE TITLE
[BUG] Warning involving lib-wrapper

### ISSUE THREAD

**Issue by themrbeasley** [ironmonk88/monks-combat-details#47]
**Describe the bug**
A warning appears upon loading the game in Foundry as the GM. The warning directs to the console.

**To Reproduce**
1. Open any world with this module enabled.
2. See warning notification.
3. Press F12

**Expected behavior**
Unknown.
Discovered in the console:

```
foundry.js:68095 Monk's Combat Details: Error detected in module. (See JS Console)
fetch @ foundry.js:68095
monks-combat-details.js:227 Uncaught (in promise) LibWrapperPackageError: lib-wrapper. Error detected in module Monk's Combat Details.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/ironmonk88/monks-combat-details
Report this issue here: https://github.com/ironmonk88/monks-combat-details/issues

== Technical Details:
Detected by libWrapper.
Package ID= monks-combat-details
Error= Can't wrap 'Draggable.prototype._onDragMouseUp', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, monks-combat-details]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at patchFunc (monks-combat-details.js:40:20)
    at Object.ready [as fn] (monks-combat-details.js:211:9)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8666:11)
    at async Game._initializeGameView (foundry.js:9908:5)
    at async Game.initialize (foundry.js:8570:5)

```

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser N/A
 - Foundry Version [11.307]
 - System [D&D5e]
 - Module version [11.05]
 - Are there any errors in the console [pasted above]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction? *Yes, I have, and I've tested it with a brand new world and encountered the same warning.*

**Additional context**
No apparent issues

**Comment by ironmonk88** [comment]
Fixed in the latest release.
