### ISSUE TITLE
[BUG] Unable to Save Combat Tracker settings

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#49]
Encounter Tracker Settings won't save while Combat Details is active.

https://github.com/ironmonk88/monks-combat-details/assets/99844555/3546f3f6-e8cd-44d6-9c1d-73ced22b6882

CD 11.04-11.06
Foundry 11.307
PF2 5.3.2

**Comment by mhilbrunner** [comment]
This is caused by the patched save function for encounter settings not checking if `game.combat` is null before trying to access `game.combat.setFlag()`.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
