### ISSUE TITLE
[BUG] Error thrown when adding a token to combat

### ISSUE THREAD

**Issue by dineshm72** [ironmonk88/monks-combat-details#50]
**Describe the bug**
Error thrown when adding a token to combat

**To Reproduce**
Right click on a PC token and select the combat HUD icon.  
Based on my settings, the combat tracker pops open as expected.  
But I get an error in console.  
Doesn't seem to impact anything that I can see, but hard to say for sure.

**Expected behavior**
No error

**Screenshots**
<img width="513" alt="image" src="https://github.com/ironmonk88/monks-combat-details/assets/2231877/2e5677a8-adb6-411e-adc5-cf2913b80c54">
<img width="397" alt="image" src="https://github.com/ironmonk88/monks-combat-details/assets/2231877/8f5c7da0-8f4d-4bb1-b037-5888fcaf0f85">

Here are my settings.  I had DF Setting Clarity on when I took these, but the issue persists with just MCD turned on. (Oh plus the Forge module that cannot be disabled on my forge host.)
<img width="452" alt="image" src="https://github.com/ironmonk88/monks-combat-details/assets/2231877/c6f5074b-1266-424d-a0dc-ff38d131dcca">
<img width="446" alt="image" src="https://github.com/ironmonk88/monks-combat-details/assets/2231877/ce40e0c9-3aa0-4231-b52a-d132c66e73fd">
<img width="444" alt="image" src="https://github.com/ironmonk88/monks-combat-details/assets/2231877/2972eeba-1cad-4183-b066-16dc7dd05523">

**Please complete as much of the following information as possible:**
 - chrome
 - v11.308
 - dnd5e 2.3.1
 - Module version 11.06
 - yes, above
 - only MCD on

**Additional context**

**Comment by ironmonk88** [comment]
This is a core issue and nothing to do with MCD.  You can get the error even if you turn MCD off.
https://github.com/foundryvtt/foundryvtt/issues/9718

**Comment by dineshm72** [comment]
Hah I didn't even think to test with no modules.  Apologies and thanks!
