### ISSUE TITLE
[BUG] Remember Previous setting only works for players if they end their own turn

### ISSUE THREAD

**Issue by dineshm72** [ironmonk88/monks-combat-details#51]
**Describe the bug**
If the GM advances the turn during combat (rather than the player clicking End Turn), the player's stored target is not updated to be the target the player had most recently selected.  When the next round comes up, the player's restored target will be the older one, not the most recent one.  

**To Reproduce**
1. Set both Clear Targets after turn and Remember Previous options
2. Select a few tokens including some players and start a combat.
3. Have players select targets and end their own turns normally.  Targets are saved as expected.
4. Have one of the players change their target, but not click end turn.  Have GM click the right arrow to advance to the next turn instead.
5. The next time that player's turn comes around, the target that is restored will be the old one, not the most recent one.  

**Expected behavior**
Current target should be saved and restored, regardless of whether the player or the GM ends the turn.

**Screenshots**
N/A

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome, safari] chrome
 - Foundry Version [e.g. v9] v11.308
 - System [e.g. D&D5e, Pathfinder 2e] 5e 2.3.1
 - Module version MCD 11.06
 - Are there any errors in the console [e.g. press F12 and look for red text] No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes, testing done with just MCD and some libraries

**Additional context**

**Comment by ironmonk88** [comment]
Fixed in the latest release.
