### ISSUE TITLE
Force Initiative rolls to be Private GM Rolls if Hide Until Turn option is checked

### ISSUE THREAD

**Issue by dineshm72** [ironmonk88/monks-combat-details#52]
**Is your feature request related to a problem? Please describe.**
Hide Until Turn is intended to conceal both what enemies are added to the combat and when in the initiative order they are place (until their turn comes around).

But the actual initiative rolls made for these NPCs are rolled using the roll setting, which is often set to Public.  This means that players can see the roll result happen in DSN and in chat cards.

It would be ideal if NPC rolls were made as Private GM rolls so that both no chat card would be created for players and the DSN dice would be ghosted (if DSN is set that way), and players won't be able to deduce where the hidden enemies will be in initiative order.

**Describe the solution you'd like**
If Hide Until Turn is set, roll all NPC initiatives as blind GM rolls.

**Additional context**

**Comment by ironmonk88** [comment]
Added to the latest release.
