### ISSUE TITLE
Add option to not remember position and size of combat tracker

### ISSUE THREAD

**Issue by JDCalvert** [ironmonk88/monks-combat-details#54]
For #42, a change was made to remember the position of the combat tracker. Can there be an option to disable this? I often need to switch in and out of full-screen mode, or sometimes use differently-sized screens or windows. Before this change, I could simply close and re-open the tracker and it would be in the correct position again (bottom right). Since this change, I have to drag it to where I want it each time.

**Comment by ironmonk88** [comment]
Added to the latest release.
