### ISSUE TITLE
[BUG] Combat Tracker fails to load

### ISSUE THREAD

**Issue by skellitor301** [ironmonk88/monks-combat-details#56]
**Describe the bug**
The combat tracker is not working properly. First I was able to add a monster to the tracker, but none of the PC's are able to be put in the tracker. I can't remove them from combat because of this unless I delete the encounter. Upon disabling combat details the combat tracker fails to load completely and remains blank.

**To Reproduce**
Unsure how this happened.

**Expected behavior**
Monsters, NPC's, PC's are able to join and roll initiative in the tracker.

**Screenshots**
![Screenshot 2023-09-16 192453](https://github.com/ironmonk88/monks-combat-details/assets/3630718/d20d35d4-d1ef-4e5a-9d69-770477f3ee16)
![Screenshot 2023-09-16 192444](https://github.com/ironmonk88/monks-combat-details/assets/3630718/9af237a6-12f7-49db-9da1-829e861e19bb)
![Screenshot 2023-09-16 191610](https://github.com/ironmonk88/monks-combat-details/assets/3630718/d0c515d6-9239-476e-a7b0-c29b7a818e0e)
![Screenshot 2023-09-16 182856](https://github.com/ironmonk88/monks-combat-details/assets/3630718/6fe8c236-872d-4e62-8187-2ff08628450b)
![Screenshot 2023-09-16 182414](https://github.com/ironmonk88/monks-combat-details/assets/3630718/c7ed6719-45db-4e96-92a5-f5403b258b8a)

**Please complete as much of the following information as possible:**
 - Foundry Version [e.g. v9]
 - System [e.g. D&D5e, Pathfinder 2e]
 - Module version
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**
Modules enabled:
Active-Auras
Active Token Effects
Additional Metric Ruler Labels
Advanced Macros
Ambient Doors
Animation Preview
Automated Animations
Automated Evocations - Companion Manager
Automated Polymorpher Manager
Auto-Rotate
Basic Rules
Beaver's Crafting Module
Beaver's Potions
Beaver's System Adaption dnd5e
Beaver's System Interface
Better Roofs
Beyond20 companion module
Break Time
Cautious Gamemaster's Pack
Character Actions List dnd5e
Chat Portrait
Combat Utility Belt
Compendium Browser
Compendium Folders
Crash's Tracking & Training (5e)
Custom Token Animations
Danger Zone
D&D5e Animations
D&D5e Character Monitor
DDB-Importer: A D&D Beyond Integrator
DF Active Lights
DF Architect
DFreds Convenient Effects
DFreds Droppables
Dice Tray
dlopen
DnD5e Drag Ruler Integration
DNDBeyond Character Sheet for 5E
Drag Ruler
Dynamic effects using Active Effects
Encounter Statistics
Enhanced Active Effects
Enhanced Terrain Layer
Find the culprit
Flying Tokens
Forgotten Adventures Battlemaps
Forien's Unidentified Items
FXMaster
GM Notes
Health Estimate
Image Hover
Initiative Double Click
Item Macro
Item Piles
Ivan Duch's Music Packs
Jack Kerouac's Animated Spell Effects
Jack Kerouac's Animated Spell Effects: Cartoon
Jack Kerouac's Animated Tokens
Jack Kerouac's Spell Effects Sequencer Plugin
JB2A - Patreon Complete Collection
Jinker's Animated Art Pack
Journal Links
Less Fog
Let's Trade 5e
Levels
lib - Color Settings
Library: Active effect manager
libWrapper
Lichtgeschwindigkeit (Lightspeed)
Magic Items
Michael Ghelfi Studios Audio Pack
Midi QOL
Monk's Active Tile Triggers
Monk's Bloodsplats
Monk's Combat Details
Monk's Enhanced Journal
Monk's Hotbar Expansion
Monk's Little Details
Monk's Scene Navigation
Monk's Shops
Monk's Sound Enhancements
Monk's TokenBar
Monk's Wall Enhancement
Moulinette Core
Moulinette Game Icons (module)
Moulinette Image Search (module)
Moulinette Scenes (module)
Moulinette Sounds & SoundPad (module)
Moulinette Tiles (module)
Multiface Tiles
Multilevel Tokens
Next Up
Ownership Viewer
Patrol
PopOut!
Potato Or Not
Secret Death Saves
Sequencer
Settings Extender
Simple Calendar
SmallTime
Small Visual Tweaks
Smart Doors
socketlib
SoundBoard by Blitz
SoundBoard Pack - Blitz Free Pack
SoundBoard Pack - Community
SoundFx Library
Splatter
Split Journal
Status Icon Counters
Super's Homebrew Compendium
Tabletop RPG Music
Tagger
Terrain Ruler
The Forge
The Forge: Compendium Library
The Forge: More Awesomeness
The Furnace
Tidy UI - Game Settings
Times Up
Token Attacher
Token Ease
Token Magic FX
Token Variant Art
VuePort: Let the Light in!
Wall Height
Warp Gate
Weather Control
Weather FX
zSync

Console error log:
commons.js:1703 Error: You are accessing the Combatant#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at Combatant._logV10CompatibilityWarning (commons.js:6642:14)
    at get data [as data] (commons.js:6542:24)
    at Object.fn (nextUp.js:250:43)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12613:13)
    at foundry.js:12594:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:12594:33)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12499:17)
    at async Combatant.createDocuments (commons.js:6110:23)
    at async Token5e.toggleCombat (foundry.js:47016:5)
    at async TokenHUD._onToggleCombat (foundry.js:71649:5)
logCompatibilityWarning @ commons.js:1703
_logV10CompatibilityWarning @ commons.js:6642
get data @ commons.js:6542
(anonymous) @ nextUp.js:250
#call @ foundry.js:724
callAll @ foundry.js:681
callback @ foundry.js:12613
(anonymous) @ foundry.js:12594
_handleCreateEmbeddedDocuments @ foundry.js:12594
_createEmbeddedDocuments @ foundry.js:12499
await in _createEmbeddedDocuments (async)
create @ commons.js:6737
await in create (async)
createDocuments @ commons.js:6110
createEmbeddedDocuments @ commons.js:6328
toggleCombat @ foundry.js:37282
toggleCombat @ foundry.js:47016
_onToggleCombat @ foundry.js:71649
TokenHUD._onToggleCombat @ monks-combat-details.js:139
_onClickControl @ foundry.js:71574
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: An error occurred while rendering MonksCombatTracker 111. Cannot read properties of undefined (reading 'has')
    at MonksCombatTracker._combatTrackerGetData (effectIconWrappers.js:74:35)
    at async MonksCombatTracker.getData (combattracker.js:18:26)
    at async MonksCombatTracker._render (foundry.js:5108:18)
    at async MonksCombatTracker._render (foundry.js:60402:5)
    at async MonksCombatTracker._render (combattracker.js:44:13)

Additional info:
Browser: 116.0.5845.188 (Official Build) (64-bit)
Foundry version: v10 Stable - Patch 7 (Build 303)
Monks Combat Details verison: 10.2
System: DND5e (2.3.1)

**Comment by skellitor301** [comment]
Further screenshots trying to play around and see what happens:

A player character and monster is in this tracker:
![Screenshot 2023-09-16 193313](https://github.com/ironmonk88/monks-combat-details/assets/3630718/547cfd96-f7f4-42aa-8ec8-6b51106bcc29)

Combat has started:
![Screenshot 2023-09-16 193425](https://github.com/ironmonk88/monks-combat-details/assets/3630718/6300c156-c929-4eea-b842-046bc9798779)

**Comment by ironmonk88** [comment]
What version of Combat Details are you using?
And could you please run Find the Culprit... because MCD hasn't used MonksCombatTracker in awhile.

The yellow warning you posted is coming from the NextUp module. But the errors are coming from the effectIconWrappers.js script... and that's not one of mine.

**Comment by skellitor301** [comment]
Monks Combat Details version: 10.2 

I have tried turning off NextUp but the problem persists. As for the effectIconWrappers.js I'm not sure which module affects that one. I'll try running find the culprit

**Comment by skellitor301** [comment]
Find The Culprit didn't work, it pointed to ZSync but even after it was disabled the issue still persisted.
I did follow the effectIconWrapper.js thread in the console which lead to the code being under Token Variant Art. Which is odd to me cause I didn't know TVA did anything in the tracker. I'll bring the issue to them and link this issue.

**Comment by skellitor301** [comment]
To follow up, I did confirm that the issue disappears when TVA is disabled. I'll assist Aedif to get the issue resolved. Thanks for the help Ironmonk :)
