### ISSUE TITLE
Unable to install mod

### ISSUE THREAD

**Issue by ThomasSessions** [ironmonk88/monks-combat-details#57]
**Describe the bug**
When I try to download Monks Combat Details I'm met with the below error:

Error: Unable to load valid module manifest data from "https://github.com/ironmonk88/monks-combat-details/releases/latest/download/module.json" Cannot read properties of undefined (reading '0') .

**To Reproduce**
Install Monks Combat Details

**Expected behavior**
The mod to not be downloaded

**Screenshots**

**Please complete as much of the following information as possible:**
 - Chrome
 - 11.311
 - D&D5e 2.3.1
 - Module version: 11.08

**Additional context**
I had no issue downloading other Monk's mods.
![MCDError](https://github.com/ironmonk88/monks-combat-details/assets/44771160/78d84a56-efb6-445d-a0b8-672e31901b27)

**Comment by Mad7eo** [comment]
I have the same problem

**Comment by Mad7eo** [comment]
A clean reinstall of foundry solved the problem! https://github.com/foundryvtt/foundryvtt/issues/10068#issuecomment-1752384181

**Comment by ironmonk88** [comment]
Closing this as I don't believe that's a Tokenbar issue, but more of a Foundry glitch.
If reinstalling works, then the install link works.
