### ISSUE TITLE
[BUG] Remember misspelled

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-combat-details#59]
Yes, this is the most important bug report ever. :)

The Remember Position module position currently appears as "Remeber."

<img width="519" alt="Screenshot 2023-10-13 at 11 04 31 PM" src="https://github.com/ironmonk88/monks-combat-details/assets/90105219/6d7bac2f-310a-4b17-b14e-23d44cbdb7ac">

**Comment by ironmonk88** [comment]
Fixed in the latest release
