### ISSUE TITLE
[BUG] Initiative rolls prompt is given for all characters in the initiative tracker at the start of every round (PF2e)

### ISSUE THREAD

**Issue by mgoldstein322** [ironmonk88/monks-combat-details#60]
**Describe the bug**
At the start of every round after the first, when the first combatant's turn begins, the GM is prompted to roll initiative for every single character in the tracker. To be clear, the roll confirmation dialogue box appears for everybody's initiative (player and NPC) and I must close all of them.

**To Reproduce**
1. Add combatants to tracker.
2. Roll all initiatives (this part doesn't seem to matter, nor does it matter who clicks the roll button; the prompts still appear if nobody has any initiative)
3. Begin encounter
4. End the round by moving to the next character in the tracker (does not occur if skipping ahead using the next round button)
5. See all prompts appear

**Expected behavior**
I expected the round to start without prompting me to roll initiative for everyone.

**Screenshots**

**Please complete as much of the following information as possible:**
 - Firefox
 - V11 313
 - Pathfinder 2e
 - 11.08
 - No
 - Yes

**Additional context**
This only occurs in one of my worlds, all settings kept equal. I find this HIGHLY suspicious, but the only difference between these worlds are the maps and character sheets, more or less.

**Comment by ironmonk88** [comment]
![image](https://github.com/ironmonk88/monks-combat-details/assets/75920956/c03e293d-0b1d-4e2f-95f4-5fe0b3c6269c)
Would you happen to have this setting turned on?

**Comment by mgoldstein322** [comment]
Oh my god lmao I was looking around all my settings for like an hour. It was this, thanks.
