### ISSUE TITLE
[BUG] Prevent Spell Changes option Prevent Change not working as expected

### ISSUE THREAD

**Issue by gambit07** [ironmonk88/monks-combat-details#62]
**Describe the bug**
There appears to be a few issues with this option at the moment. The first is that it does not seem to work with Warlock Pact slots at all. The second is that it does not work consistently for standard spell slots.

**To Reproduce**
Warlock Pact Slots:
1. With Prevent Change set in settings, login as a player character that is a warlock, level 8.
2. Put the player character in combat and remove all spell slots as GM
3. Modify players pact spell slots as the player character
4. Player will be able to modify at will

Standard Spell Slots
5. With Prevent Change set in settings, login as a player character that is a wizard, level 8
6. Put the player character in combat and remove all spell slots as GM
7. Take a long rest as the player character
8. Any slot levels above 1st will be recovered. Player still will be unable to manually change any spell slot within the character sheet. This one is less an issue because players aren't long resting during combat, but figured it may give more context

**Expected behavior**
The expectation is that no spell slot changes would occur for a player if a player is in combat with Prevent Change set in settings either through the character sheet or through long rest

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version 11.315
 - System 5e 2.3.1 & 2.4
 - Module version 11.09
 - Are there any errors in the console No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes but difficult to test due to it being specifically a client issue and not a gm issue

**Additional context**

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
