### ISSUE TITLE
[BUG] Most important bug report ever

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-combat-details#63]
<img width="537" alt="Screenshot 2023-12-01 at 10 35 11 PM" src="https://github.com/ironmonk88/monks-combat-details/assets/90105219/fd7343b6-094a-4bd5-a990-38ad3cf6b942">

:)

Should be "Remember Position", not "Remeber Position"

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
