### ISSUE TITLE
[BUG] Spell Preparation changes warning in combat happens on every cast

### ISSUE THREAD

**Issue by itteerde** [ironmonk88/monks-combat-details#64]
**Describe the bug**
The changing spell preparation in combat message happens without changing the spell -- just when casting it.
![image](https://github.com/ironmonk88/monks-combat-details/assets/8367477/e64bc13d-849b-44ef-9f34-d9aefa6623ed)

**To Reproduce**
1. start combat
2. cast a spell (that is prepared)

**Screenshots**

**Please complete as much of the following information as possible:**
 - Chrome fully updated (and been reproduced on another server)
 - Foundry Version 11.315
 - System dnd 2.4
 - Module 11.09
 - Are there any errors in the console no
 - Have you tried using `Find the Culprit` does happen with Combat Details being the only Module active, too

**Comment by burekitas** [comment]
mine is set to prevent changes but it also prevents **using** spell slots now. so whenever a player casts a spell and telling the game to use a spell slot they get a message they can't.
![PHOTO-2023-12-07-00-57-26](https://github.com/ironmonk88/monks-combat-details/assets/81911369/4c1fd3d1-05b9-4653-b614-5c20a2cbe5dd)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
