### ISSUE TITLE
[BUG] combat tracker auto scroll issue

### ISSUE THREAD

**Issue by ditzer252** [ironmonk88/monks-combat-details#66]
The combatants at the top of the list are not completely visible when using auto scroll feature.

![image](https://github.com/ironmonk88/monks-combat-details/assets/81697575/4b038db0-0350-4a03-a028-f1c08058d2fc)

 - Browser - Edge
 - Foundry Version 11.315
 - System PF2e 5.10.5
 - Module version 11.09
 - Are there any errors in the console NO
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. YES,

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
