### ISSUE TITLE
[BUG] Mark Defeated, PCs

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#67]
D&D 5e: this setting no longer works on PCs. NPCs are fine. No errors.

https://github.com/ironmonk88/monks-combat-details/assets/99844555/03144047-bf74-46c9-9a2c-0b08181a0d4b

Foundry 11.315
Combat Details 11.09
D&D 5e 2.4.1

**Comment by ckdragons** [comment]
This also happens in PF1e 9.6.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
