### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#68]
Occurs when adjusting NPC HP.

https://github.com/ironmonk88/monks-combat-details/assets/99844555/e0860247-cf26-4fd8-8483-74755449352c

CD 11.09
D&D 5e 2.4.1
Foundry 11.315

**Comment by Dyrnwyrm** [comment]
Are you unable to move the dead token on the canvas right?just asking if this is related to my issue

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
