### ISSUE TITLE
Add macro support to the Add Placeholder Combatant feature

### ISSUE THREAD

**Issue by Motara7** [ironmonk88/monks-combat-details#69]
The Add Placeholder Combatant featureat the bottom of the Combat Encounters pane is a great feature. It's cumbersome to use, however, mostly because it does not appear when the Combat Encounters pane is popped out.

**Minmal Request**
Make it to the Add Placeholder Combatant button also appears when the Combat Encounters pane is popped out.

**Better Request**
Allow for/provide a macro to open the Add Placeholder Combatant dialogue. This would alow a script call to be added to an action (Feature, Spell, etc.).

**Ideal Request**
Allow for/provide a macro to auto-complete the Add Placeholder Combatant dialogue. For example, I could add a script call to an Acid Arrow spell that would pull the name of the spell (Acid Arrow) and put it in the "Displayed Name" field, the "Thumbnail Image" could be pulled from the image attached to the spell, and add the duration of the spell into the "Remove After (rounds}" field. Then I would just review trhe info and/or make adjustments and click Create Combatant.

**Comment by ckdragons** [comment]
I am also experiencing this issue. The "Add Placeholder Combatant" is missing from Combat Encounters popout. Cumbersome to switch to normal Combat Encounters tab to use.
Foundry 11.315
Pathfinder 1E 9.6
Combat Details 11.09

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
