### ISSUE TITLE
Combat sounds still occur even though all options are disabled

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-combat-details#70]
![image](https://github.com/ironmonk88/monks-combat-details/assets/84493092/075176a2-0fc3-47d4-98ab-09c06f8bb921)

Even with these options set and a F5 refresh, the sounds still happen with on each actor's turn. I'm the GM. Using Foundry 11.315, Pathfinder 1e 9.6, and Combat Details 11.09.

**Comment by ironmonk88** [comment]
Can't replicate the issue.
Did you turn off the Core combat sounds?
![image](https://github.com/ironmonk88/monks-combat-details/assets/75920956/88bae69b-518f-4852-88e1-bca3b0ffc8b6)

**Comment by ckdragons** [comment]
I will try that. Thank you.
