### ISSUE TITLE
Can´t make the new playlist feature to work

### ISSUE THREAD

**Issue by jacksands** [ironmonk88/monks-combat-details#75]
I'm very happy that this was implemented!!!  thank you very much!
but I was not able to make it works...

If you can help I appreciate!

thank once again!

**Describe the bug**
I Have tried the new "Combat Playlist" but it do not play...  only the current track pauses, but the playlist do not start

**To Reproduce**
1. have a playlist 
2. In combat Tracker settings choose the playlist
3. In the settings make sure the "volume" setting for the module is ok, also the volumes in the foundry
4. start a combat

**Expected behavior**
the playlist should play

**Screenshots**
![monk](https://github.com/ironmonk88/monks-combat-details/assets/7229143/7b223392-df09-4d7a-b3dd-bfee49a61714)

![monk 2](https://github.com/ironmonk88/monks-combat-details/assets/7229143/47e98894-561f-46cf-bc48-7fb799f22963)

**Please complete as much of the following information as possible:**
- tested with all modules of
- error on console 
- on console the error flags Monks enhanced journal, but it is not active in this world...

**Additional context**

**Comment by ironmonk88** [comment]
Pretty sure this was fixed in the last release.

**Comment by ironmonk88** [comment]
Closing this as I'm pretty sure it was fixed in the last release.
