### ISSUE TITLE
[BUG] "Switch to Chat Tab" does not work as a global setting

### ISSUE THREAD

**Issue by peterprokurist** [ironmonk88/monks-combat-details#76]
The "Switch to Chat Tab" setting only works for the GM, even though it is marked as a "Global Setting". Players remain in their selected tab.

![image](https://github.com/ironmonk88/monks-combat-details/assets/115837717/63d5a42f-928c-4b2f-b506-25adae9e7700)

**Please complete as much of the following information as possible:**
 - Browser: GM (Chrome), Player (VTT Desktop Client from TheRipper)
 - Foundry Version 11
 - System: SWADE 
 - Module version: current

I disabled all modules except "Monk's Combat Details" and "Find the culprit"

There are the following error messages with F12:

![image](https://github.com/ironmonk88/monks-combat-details/assets/115837717/58a9adec-f4bc-4f3b-830b-900a74730556)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
