### ISSUE TITLE
[Feature Request] Play random songs from combat playlist

### ISSUE THREAD

**Issue by nschoenwald** [ironmonk88/monks-combat-details#77]
As is, the combat playlist feature plays the same song every time. I would love for it to shuffle the songs in that playlist, or at least to have the option to do so.

**Comment by ironmonk88** [comment]
That's a function of the setting for the playlist.  You can already do that, you just need to tell the playlist to shuffle.
![image](https://github.com/ironmonk88/monks-combat-details/assets/75920956/49002db6-d6d8-45bc-a6e0-6db01aa2d276)

**Comment by ironmonk88** [comment]
Closing this as it's not functionality of Combat Details
