### ISSUE TITLE
Combat Display Bars from macro?

### ISSUE THREAD

**Issue by ksignorini** [ironmonk88/monks-combat-details#78]
I tried to set the Combat Display Bars from a macro:

```
const updates = [];
for(const actor of game.actors) if (actor.type === "npc") updates.push({
  _id: actor.id,
  "prototypeToken.displayName": CONST.TOKEN_DISPLAY_MODES.HOVER,
  "prototypeToken.displayBars": CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
  "prototypeToken.flags.monks-combat-details.displayBarsCombat":40
});
await Actor.updateDocuments(updates);
```

and it doesn't show it as any different on the prototype token. However, inspecting the object shows 40 as the value. 

When I drag the prototype onto a scene and check the token, the token _does_ have the value set.

Am I doing this wrong? Is it a bug in the module?

<img width="1342" alt="image" src="https://github.com/ironmonk88/monks-combat-details/assets/6867660/ec192483-2850-4e3d-a3a0-1434f499c31d">

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
