### ISSUE TITLE
After hitting 'begin combat' button can't select any tokens in combat

### ISSUE THREAD

**Issue by DM12345Z** [ironmonk88/monks-combat-details#80]
**Describe the bug**
After hitting 'begin combat' button can't select any tokens in combat

**To Reproduce**
1. Add a token(s) to the combat tracker and click and 'begin combat'
2. Try to select any token on the map that is currently in combat.  You won't be able to select them.  You can't even double click on them to see the character sheet.  Also the combat tracker does not pop out.

**Expected behavior**
You should be able to see the combat tracker pop out when you begin combat as well as be able to select tokens on the map that are in combat.  

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser **Chrome**
 - Foundry Version **v11 315**
 - System **Shadow of the Demon Lord**
 - Module version **11.15**
 - Are there any errors in the console - **NO**
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.  **I've tried it as the only module and its still not working.**

**Additional context**
**It used to work just fine and now its not working.  Not only can you not select any tokens in the combat, but the combat initiative tracker doesn't pop out.  You can select tokens that are not in the combat just fine.**

**Comment by AetherianRPG** [comment]
I have this issue as well. It used to work on version 11.12, but stopped working after 11.13. Here is a screenshot of the console:

![Monks001](https://github.com/ironmonk88/monks-combat-details/assets/68928934/cf36e00f-0a99-476b-9e70-d28259aff8bc)

**Comment by ckdragons** [comment]
This issue is still happening with version 11.15.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
