### ISSUE TITLE
[BUG] Placeholder breaks the group from Combat Tracker Extensions module

### ISSUE THREAD

**Issue by stalker168** [ironmonk88/monks-combat-details#82]
**Describe the bug**
There is a Combat Tracker Extensions module that allows you to do group initiative in the DnD5 system.
But if you add a placeholder combatant to the initiative, groups break.
The settings button for the Combat Tracker Extensions module disappears. All groups below the combatant's initiative are broken.
When the combatant is removed, everything returns to its place.

Console error after adding a combatant:
```
combat-tracker-extensions.js:563  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'innerHTML')
    at Object.fn (combat-tracker-extensions.js:563:32)
```

Before adding a combatant
![image](https://github.com/ironmonk88/monks-combat-details/assets/31571343/f1ee11f7-3ee0-40ed-8526-d6cfa13a6126)
After adding a combatant
![image](https://github.com/ironmonk88/monks-combat-details/assets/31571343/24dbd2a6-1e3a-4b0a-9032-06dac2511cd2)

![image](https://github.com/ironmonk88/monks-combat-details/assets/31571343/abfc384f-015b-4644-bf3a-7e9514aa8e67)

**To Reproduce**
1. Create a fight
2. Add Placeholder Combatant
3. See error

**Expected behavior**
Using the Combat Enhancements module in conjunction with Combat Tracker Extensions shows that the group can adjust to changes in the initiative's turn.
From this I can conclude that it is possible to add a combatant without breaking groups. After adding a combatant, the groups will adjust to the new participant, preserving their integrity.

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser [chrome]
 - Foundry Version [v11.315]
 - System [D&D5e 3.1.2]
 - Module version Monk [11.15]
 - Module version Combat Tracker Extensions [1.4]

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
