### ISSUE TITLE
[BUG] D&D 3.5

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-combat-details#84]
Multiple issues:

* Unable to pop out the combat tracker with module enable (start of video, no errors).
* Unable to move or interact with tokens in combat with module enabled.
* **Lot** of errors every when moving the mouse while combat is enabled.

https://github.com/ironmonk88/monks-combat-details/assets/99844555/7ca72aa8-977b-42a1-a77c-1bd13a5e56e1

Foundry 11.315
D&D 3.5 2.4.3
Combat Details 11.15

**Comment by ironmonk88** [comment]
That would be an issue with DnD 3.5 not properly calling the CombatTracker getData function.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
