### ISSUE TITLE
[BUG] Installation fails with error

### ISSUE THREAD

**Issue by luminousgrue** [ironmonk88/monks-combat-details#86]
**Describe the bug**
Attempting to install Monk's Combat Details from the Foundry admin panel fails and returns the following error message:
"Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/ironmonk88/monks-combat-details/11.16/module.json" Cannot read properties of undefined (reading '0')"

**To Reproduce**
1. Find Monk's Combat Details in Install Module window
2. Click on 'Install'
3. Read error message at top of screen
4. See that module has not installed in Modules panel

**Expected behavior**
The error should not appear, and Monk's Combat Details should be installed.

**Screenshots**
![image](https://github.com/user-attachments/assets/817af651-f482-4b60-a9f3-d3c82b44c410)

**Please complete as much of the following information as possible:**
 - Chrome Version 126.0.6478.127 (64-bit)
 - Foundry Version 10 Build 315
 - System N/A
 - Module version 11.16
 - Are there any errors in the console [e.g. press F12 and look for red text]
```
 Uncaught (in promise) Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/ironmonk88/monks-combat-details/11.16/module.json"
Cannot read properties of undefined (reading '0')
    at Module.installPackage (file:///home/ubuntu/foundryvtt/resources/app/dist/packages/views.mjs:1:1803)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///home/ubuntu/foundryvtt/resources/app/dist/server/views/setup.mjs:1:2108)
```
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. // Not applicable

**Comment by ironmonk88** [comment]
11.16 isn't going to load on v10 Foundry.
Try the last 10.x version instead. https://raw.githubusercontent.com/ironmonk88/monks-combat-details/10.2/module.json
Otherwise I don't support older versions, and the latest one is 12.01

**Comment by luminousgrue** [comment]
Hi thanks, the 10 was a typo - as per my screenshot my Foundry version is actually **11** 315

Nevertheless, thank you for pointing me in the right direction.
